stages:
  - build
  - package
  - deploy

variables:
  NAMESPACE: bryce-boot
  WORKLOAD: bryce-boot
  HARBOR_URL: core.harbor.brycehan.com
  IMAGE_NAME: $HARBOR_URL/bryce/bryce-boot:latest
  HOST: api.boot.brycehan.com
  PORT: 8090

build:
  stage: build
  image: $HARBOR_URL/bryce-docker/maven:latest
  when: always
  only:
    - main
  script:
    - mvn package -Dmaven.test.skip=true
  artifacts:
    name: "${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}"
    expire_in: 1hrs
    paths:
      - bryce-boot-server/target/*.jar
  tags:
    - bryce-runner

package:
  stage: package
  image: $HARBOR_URL/bryce-docker/buildah:latest
  when: on_success
  only:
    - main
  script:
    - /buildah.sh -t=$IMAGE_NAME
  tags:
    - bryce-runner

deploy:
  stage: deploy
  image: $HARBOR_URL/bryce-docker/kubectl:latest
  when: on_success
  only:
    - main
  script:
    - /deploy.sh -n=$NAMESPACE -w=$WORKLOAD -i=$IMAGE_NAME -h=$HOST -p=$PORT
  tags:
    - bryce-runner
