# spring配置
spring:
  # Spring应用
  application:
    # 名称
    name: bryce-boot
  servlet:
    # 上传文件
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 1024MB
  # 资源信息
  messages:
    # i18n国际化资源文件路径
    basename: i18n/messages
  data:
    # data redis配置
    redis:
      # 主机
      host: localhost
      # 端口，默认为6379
      port: 6379
      # 数据库索引
      database: 0
      password:
  # Jackson配置
  jackson:
    # 序列化
    serialization:
      # 缩进输出
      indent-output: true
  profiles:
    active: bryce,sms,dev
# mybatis plus配置
mybatis-plus:
  # mapper.xml映射文件位置
  mapper-locations: classpath*:com/brycehan/boot/*/mapper/xml/*Mapper.xml
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: null
  global-config:
    banner: false
    # 数据库相关配置
    db-config:
      id-type: none
      # 逻辑已删除值
      logic-delete-value: 1
      # 逻辑未删除值
      logic-not-delete-value: 0
# 服务配置
server:
  # 服务器HTTP端口
  port: 8090
  servlet:
    # 应用的访问路径
    context-path: /
  # undertow Web容器
  undertow:
    threads:
      # 工作线程数
      worker: 400
# 数据翻译插件
easy-trans:
  #启用redis缓存 如果不用redis请设置为false
  is-enable-redis: true
  #启用全局翻译(拦截所有responseBody进行自动翻译)，如果对于性能要求很高可关闭此配置
  is-enable-global: true
  #启用平铺模式
  is-enable-tile: true
  #字典缓存放到redis 微服务模式请开启
  dict-use-redis: true






