# spring配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/bryce_boot?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useServerPrepStmts=true&cachePrepStmts=true
    username: root
    password: root
  data:
    # data redis配置
    redis:
      host: redis
      port: 6379
      database: 0
# 接口配置
springdoc:
  api-docs:
    enabled: false
# 日志配置
logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSSXXX
  file:
    path: /var/log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      total-size-cap: 1GB
  level:
    root: info