# spring配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.10:3306/bryce_boot?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
  devtools:
    restart:
      enabled: false
  data:
      # data redis配置
    redis:
      host: 192.168.0.10
      port: 6379
      database: 0
# mybatis plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# 接口配置
springdoc:
  api-docs:
    enabled: true
# 日志配置
logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSSXXX
  file:
    path: /var/log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      total-size-cap: 1GB
  level:
    root: debug
    web: debug
    com.brycehan.boot: debug
    com.brycehan.boot.system.mapper: debug
    org.springframework: info
