# 项目名称
name: bryce-boot

# 服务
services:
  # mysql 服务
  boot-mysql:
    container_name: boot-mysql
    image:  public.ecr.aws/docker/library/mysql:8.0.33
    ports:
      - "3306:3306"
    networks:
      - boot
    volumes:
      - ./mysql:/etc/mysql/conf.d
      - ./mysql/db:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=bryce_boot
      - MYSQL_ROOT_PASSWORD=root
    restart: unless-stopped
  # redis 服务
  boot-redis:
    container_name: boot-redis
    image: public.ecr.aws/docker/library/redis:7.2.7
    ports:
      - "6379:6379"
    networks:
      - boot
    volumes:
      - ./redis/redis.conf:/opt/redis.conf
      - redis-data:/data
    command:
      - /opt/redis.conf
    restart: unless-stopped
  # server 服务
  boot-server:
    container_name: boot-server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    networks:
      - boot
    depends_on:
      - boot-redis
      - boot-mysql
    restart: unless-stopped

# 存储卷
volumes:
  mysql-data: {}
  redis-data: {}

# 网络
networks:
  boot:
    driver: bridge