sms:
  config-type: yaml
  is-print: false
  login-template-id: SMS_463676981
  register-template-id: SMS_463676982
  number_text_messages_sent_per_day: 5
  blends:
    sms1:
      #框架定义的厂商名称标识
      supplier: alibaba
      #有些称为accessKey有些称之为apiKey，也有称为sdkKey或者appId。
      access-key-id: ...
      #称为accessSecret有些称之为apiSecret。
      access-key-secret: ...
      #您的短信签名
      signature: BryceAdmin
      #短信自动重试间隔时间  默认五秒
      retry-interval: 5
      # 短信重试次数，默认0次不重试，如果你需要短信重试则根据自己的需求修改值即可
      max-retries: 0



