bryce:
  # 项目配置
  application:
    # 名称
    name: Bryce Boot
    # 版本
    version: @project.version@
    # 版权年份
    copyright-year: 2023
    # 实例演示开关
    demo-enabled: true

  # 代码生成
  generator:
    table-prefix: brc_
    package-name: com.brycehan.boot

  # id 生成器
  id:
    # 机器码
    worker-id: 0
    # 机器码位长
    worker-id-bit-length: 6
    seq-bit-length: 10
    # 起始时间
    base-time: 1692948713117

  # 线程池
  thread-pool:
    # 核心线程数
    core-pool-size: 100
    # 最大线程数
    maximum-pool-size: 500
    # 存活时间（单位：秒）
    keep-alive-time: 60
    # 任务队列的任务数
    work-queue-size: 1000

  # jwt 令牌
  jwt:
    # 令牌密钥
    secret: UZCiSM60eRJMOFA9mbiy
    # 权限键
    authorities-key: auth
    #令牌有效期（默认2小时）
    token-validity-in-seconds: 7200

  # 验证码配置
  captcha:
    width: 235
    height: 30
    length: 5
    expiration: 10

  # 权限过滤
  auth:
    ignore-urls:
      all:
        - /generator-ui/**
        - /pay/alipay/trade/notify
        - /pay/wechatPay/native/notify
        - /pay/wechatPay/refund/notify
        - /pay/product
        - /mp
        - /error
      get:
        - /
        - /webjars/**
        - /swagger-ui/**
        - /swagger-resources/**
        - /v3/api-docs/**
        - /doc.html
        - /favicon.ico
        - /attachment/**
        - /captcha/**
        - /sms/**
        - /register/enabled
      post:
        - /auth/loginByAccount
        - /auth/loginByPhone
        - /register

  # xss 过滤
  xss:
    enabled: true
    exclude-urls:
      - /system/notice
      - /mp

  # 用户配置
  user:
    password:
      # 密码最大错误次数
      max-retry-count: 5
      # 密码锁定间隔（默认10分钟）
      lock-duration-minutes: 10

  # 存储配置
  storage:
    enabled: true
    config:
      # 存储类型 local|aliyun|tencent|qiniu|huawei|minio
      type: local
      domain: http://localhost:${server.port}
    local:
      # 路径 System.getProperty("user.home") + projectName + "/attachment";
      path: ${user.home}/bryce-boot/attachment
