bryce:
  # 微信公众号
  mp:
    enabled: true
    # APPID
    app-id: wx264fcac63168e5bb
    # APP SECRET
    secret: c7b629c2979fe1245ed8c5e4017fb246
    # 令牌
    token: Dg03nBzjFXx5gwyedimoytRMSaPyrO9d
    # EncodingAESKey
    aes-key: UDuLFDcmy51111111111111111111111
