# spring 配置
spring:
  application:
    name: bryce-boot  # 应用名称
  profiles:
    include: bryce,email,sms,mp,ma,pay
    active: dev   # 环境 dev|test|prod
  # Jackson 配置
  jackson:
    # 时区
    time-zone: GMT+8
    # 空值处理
    default-property-inclusion: always
  servlet:
    # 上传文件
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 1024MB

# 服务器配置
server:
  # 服务器 HTTP 端口
  port: 8090
  servlet:
    # 应用的访问路径
    context-path: /

# 接口文档
knife4j:
  enable: true
  basic:
    enable: false # 开启登录
    username: swagger
    password: 123456

# mybatis plus 配置
mybatis-plus:
  # mapper.xml 映射文件位置
  mapper-locations:
    - classpath*:com/brycehan/boot/*/mapper/xml/*Mapper.xml
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
  # 全局配置
  global-config:
    banner: false
    # 数据库相关配置
    db-config:
      # 用户输入ID
      id-type: none
      # 逻辑已删除值
      logic-delete-value: true
      # 逻辑未删除值
      logic-not-delete-value: false

# easy trans 数据翻译插件
easy-trans:
  #启用redis缓存 如果不用redis请设置为false
  is-enable-redis: true
  #启用全局翻译(拦截所有responseBody进行自动翻译)，如果对于性能要求很高可关闭此配置
  is-enable-global: true
  #启用平铺模式
  is-enable-tile: true
  #字典缓存放到redis 微服务模式请开启
  dict-use-redis: true
  # MP为 3.5.3.2版本以上的3.x 版本请设置为true，否则可能会出现找不到对应方法的问题
  mp-new: true




