spring: # spring 配置
  datasource: # 数据源配置
    dynamic:
      primary: master # 设置默认的数据源或者数据源组,默认值即为 master
      p6spy: false
      hikari: # Hikari 连接池全局配置
        connection-timeout: 30000 # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没有可用的连接则发生 SQLException，默认：30秒
        minimum-idle: 2           # 最小空闲连接数
        maximum-pool-size: 10     # 最大连接数
        idle-timeout: 600000      # 连接超时的最大时长（毫秒），超时则被释放（retired），默认：10 分钟
        max-lifetime: 1800000     # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认：30分钟
        connection-test-query: select 1
      datasource:
        master:
          # mysql 8
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/bryce_boot?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&nullDatabaseMeansCurrent=true&useServerPrepStmts=true&cachePrepStmts=true
          username: root
          password: root
          # postgresql
#          driver-class-name: org.postgresql.Driver
#          url: jdbc:postgresql://localhost:5432/postgres
#          username: bryce_boot
#          password: 123456
          # 达梦
#          driver-class-name: dm.jdbc.driver.DmDriver
#          url: jdbc:dm://localhost:5436/bryce_boot?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullDatabaseMeansCurrent=true
#          username: bryce_boot
#          password: 123456

  data: # data 配置
    redis: # data redis 配置
      # 主机
      host: localhost
      # 端口，默认为6379
      port: 6379
      # 数据库索引
      database: 0
      # 连接超时时长
      connect-timeout: 6s

  task: # 任务配置
    scheduling: # 定时任务
      thread-name-prefix: bryce-scheduling-
      pool:
        size: 8
    execution:  # 异步任务
      thread-name-prefix: bryce-task-
      pool:
        core-size: 20
        max-size: 100
        queue-capacity: 20
        keep-alive: 60s

# 自定义配置
bryce:
  jwt:
    # 测试24小时有效期
    token-validity-in-seconds: 86400

# 日志配置
logging:
  level:
    root: info
    com.brycehan.boot.pay: debug
    org.quartz: warn