# spring 配置
spring:
  application:
    # 应用名称
    name: bryce-boot
  profiles:
    include: bryce,bpm
    # 环境 dev|prod
    active: dev
  # Jackson 配置
  jackson:
    # 空值处理
    default-property-inclusion: always

  servlet:
    # 上传文件
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 1024MB
  mvc:
    servlet:
      # 启动时初始化 mvc servlet
      load-on-startup: 0

# 服务器配置
server:
  # 服务器 HTTP 端口
  port: 8090

# 接口文档
knife4j:
  enable: true
  basic:
    enable: false # 开启登录
    username: swagger
    password: 123456

# mybatis plus 配置
mybatis-plus:
  # mapper.xml 映射文件位置
  mapper-locations:
    - classpath*:com/brycehan/boot/*/mapper/xml/*Mapper.xml
  type-aliases-package: com.brycehan.boot.*.entity.po
  # 原生配置
  configuration:
    # 是否开启下划线和驼峰命名的映射
    map-underscore-to-camel-case: true
    # 是否开启二级缓存
    cache-enabled: false
    # 查询返回map的时候，是否返回null值对应的字段的entry
    call-setters-on-nulls: true
    # 设置参数值为null的字段的jdbcType为null
    jdbc-type-for-null: 'null'
    # 枚举类型处理器
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  # 全局配置
  global-config:
    # 是否显示banner
    banner: false
    # 数据库相关配置
    db-config:
      # 用户输入ID
      id-type: input
      # 逻辑已删除值
      logic-delete-value: now()
      # 逻辑未删除值
      logic-not-delete-value: 'null'

