bryce:
  pay:
    # 微信支付
    wechat-pay:
      enabled: false
      # 商户号
      mch-id: 1558111111
      # 商户API证书序列号
      mch-serial-no: 3434596433111111111111111111111111111111
      # 商户私钥文件
      private-key-path: classpath:apiclient_key.pem
      # APIv3密钥
      api-v3-key: UDuLFDcmy51111111111111111111111
      # APIv2密钥
      partner-key: T6m9iK73b01111111111111111111111
      # APPID
      appid: wx74862e0d11111111
      # 小程序APPID
      ma-appid: wx74862e0d11111111
      # 微信服务器地址
      domain: https://api.mch.weixin.qq.com
      # 接收结果通知地址
      notify-domain: https://d5a9-112-36-235-21.ngrok-free.app

    # 支付宝支付
    alipay:
      enabled: false
      # 应用ID,您的APPID，收款账号既是您的APPID对应支付宝账号
      app-id: 9021000135613930
      # 商户PID,卖家支付宝账号ID
      seller-id: 2088721031562115
      # 支付宝网关 https://openapi.alipaydev.com/gateway.do
      gateway-url: https://openapi-sandbox.dl.alipaydev.com/gateway.do
      # 商户私钥，您的PKCS8格式RSA2私钥
      merchant-private-key: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCdUlO/FzDkkgBLIsxMNlKg0Qbfqz73dC4WWo853sqIzDB3Ivey1oaBb2rcrC8TRaRjrvpAN6INaxwI61EbNQS/WYWILnZ9CodrgZWnzLWZcBhtBZ6oHYqhFxF2JRVLQUV8lI+Mzn1kUr10sEwSYCn6mZw6X0TjO4yRsixJJSwidzK+x3nMlpL0Jz7q1UUZwkXY7WkqvIfc6f++vadT9L8CsHb19b18LZPWgwZmSoHhTAeLatl31PivC3nDEfndfGwqU+ddzmyu3Dmq+D8qR0JJklLN4/f/cgFkLcYSXoC+GsKQAZY/eHRPFmQlLACcTjper0DiDzHN+CPuW6EeHXMTAgMBAAECggEABxHJA6BGKS9KZhX1OkOCqQlblrd6R+Jno8eEAiS50zXhw6jFmrq7JpvcIHh4URRjE7usMTCOzq2Of/QbG+7g/LxIHNuBpZLQjQswr26qhm+cGWIURBe3wA9qUHXQJCaVuchvPvOUfOqe6tx1PqolmMZIV/MqBFALvAxWox7Rgebo1N0RaDrZWzWnIdiZgJNV4Xs3nR9hiQKy+9vq5b84dfg/NAPGx+g3ofr7uOwsEPt/xkpJStjF8rDTgyrHYJ7u/J58GB7zDynAwGCAG3gmUBNgD6BfgEnhpLpK/cnCErg47SnNCtsYBcN9BWCHZr5IbG61AmZY/TsO5E4xUxszaQKBgQD8WUVm8sS/VaCq8LNeRJ2RQJpqhlSo8K5lKfaZHIajwzF56LEey41/U01Mb9Nlt0/oZ/zsFkuve4DLF2IqSOYVtdLqIe4kRRbwUCGME+DecWJnjnSmIr8Ts8FQ0d+huu+ZSE4Js04ob09Pq/93P1JyNVOAhj6HIemc63GKpSIODQKBgQCfmRCGANPcp5C4AicsiGaktAueju9rcx+G4xt7mY935UqOdTwIKO6zvuAK0CO/fIQu+jiA4nF8XGrDL53bR+P/ZKRkthd3QczxjBq4p0jw0grgS3retpd3J5spiA7r1gceCHE0sbSx2hU+/gmcdqeI/YktAhNOTivl53ApT0xdnwKBgH4Gr2x8rdnIj9cPIuVfaznRg8zTjZBZsx7+2BMbdfpvT1RM67gvfFksZxxXdMIFzLiKxnu5ns7i5S2IXhQ0GASbq9wWWfJvNseJnVdxzgoJolWJhaQ7EiZqzY7pYcBJtcNdouuhStVS0c8+XPVXAHvdOfikErI2M4+U3j2Zvuo5AoGAOCYw0wRdhUcKukI/qAJBIncZk2o0P3hcQieKlrya5hKsXVxPh4tnF6PyzLsXqJnVI3XzBR0l0hvtj8gj4G71fvfYgnox3UowIVcqW4a3Ocqb+vdzPgG9XjV3+G+e2EgPbviHY4OVz/CrAuN7XCm+nYqdhVEym50TAqqfIll8w38CgYAsGHA8aofQu/bCnBGtwndBRpx7brdMuRRJY60uEKtIBWkvY0rS8jQayp3qMnwLbtEmgPpwEVvBh5OdfySCcy+SCHc1/Lbwpg9UHPzIivrkUXnVzPpaywNySQH7FrSq6L8mCYOBOREMPCD1OOjgDCQuL+Le7c0UAdqOXAQTkX0Dwg==
      # 支付宝公钥,查看地址：https://openhome.alipay.com/platform/keyManage.htm 对应APPID下的支付宝公钥
      alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqnvwRx0UsroRkOLRGecdR4c7pXM+V9Xsr1Y9tPlWJ2iNDwSuXSQhUcQdTsAYy/aMfZB7c19pXjHRfSlhLhRifHmaYv176ganWxq0lMJBjoq20/oSOKIV+L5+txn/1xduazyW6IVZInInT00Pcyzj2RLzxu+Pd3IqshIeXbWsmbPb1gfYV6NLN6RE1DSWlnY3r5Pqekla7TrAkcktPZkuu789G1V/VFn0Dz1VLSHQ7i7nnPJvSyDIbq54ixVnharlqPYEEVpfzEIwChX3bTYSqH4S3fMI6DL8dAEeYRVDYN0Xw+v6Jwsct6B06KawW4P35Ai/qkFm8fho1DQy2+OlvwIDAQAB
      # 接口内容加密秘钥，对称秘钥
      content-key: 7DzmY4H7IYUfJUNnID7Fzw==
      # 页面跳转同步通知页面路径
      return-url: http://localhost:8090/#/success
      # 服务器异步通知页面路径  需http://格式的完整路径，不能加?id=123这类自定义参数，必须外网可以正常访问
      notify-url: https://d5a9-112-36-235-21.ngrok-free.app/pay/alipay/trade/notify
